"""empty message

Revision ID: 11a443c1efc9
Revises: d4f6a750e94c
Create Date: 2025-02-17 13:22:47.080051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11a443c1efc9'
down_revision: Union[str, None] = 'd4f6a750e94c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('location', sa.String(length=100), nullable=True))
    op.add_column('posts', sa.Column('hashtags', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'hashtags')
    op.drop_column('posts', 'location')
    # ### end Alembic commands ###
