"""empty message

Revision ID: 3bcda1266e01
Revises: b78114db6960
Create Date: 2025-02-16 18:48:30.986449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bcda1266e01'
down_revision: Union[str, None] = 'b78114db6960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('password', sa.String(length=50), nullable=False))
    op.add_column('user_account', sa.Column('profile_img_path', sa.String(), nullable=True))
    op.add_column('user_account', sa.Column('bio', sa.String(length=100), nullable=True))
    op.alter_column('user_account', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_account', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('user_account', 'bio')
    op.drop_column('user_account', 'profile_img_path')
    op.drop_column('user_account', 'password')
    # ### end Alembic commands ###
