"""empty message

Revision ID: 96747a25b227
Revises: 027a913ec605
Create Date: 2025-02-17 14:26:10.977626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96747a25b227'
down_revision: Union[str, None] = '027a913ec605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('follow_request_requested_id_fkey', 'follow_request', type_='foreignkey')
    op.drop_constraint('follow_request_requester_id_fkey', 'follow_request', type_='foreignkey')
    op.create_foreign_key(None, 'follow_request', 'user_account', ['requester_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'follow_request', 'user_account', ['requested_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('following_followed_id_fkey', 'following', type_='foreignkey')
    op.drop_constraint('following_follower_id_fkey', 'following', type_='foreignkey')
    op.create_foreign_key(None, 'following', 'user_account', ['follower_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'following', 'user_account', ['followed_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('posts_user_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'user_account', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_user_id_fkey', 'posts', 'user_account', ['user_id'], ['id'])
    op.drop_constraint(None, 'following', type_='foreignkey')
    op.drop_constraint(None, 'following', type_='foreignkey')
    op.create_foreign_key('following_follower_id_fkey', 'following', 'user_account', ['follower_id'], ['id'])
    op.create_foreign_key('following_followed_id_fkey', 'following', 'user_account', ['followed_id'], ['id'])
    op.drop_constraint(None, 'follow_request', type_='foreignkey')
    op.drop_constraint(None, 'follow_request', type_='foreignkey')
    op.create_foreign_key('follow_request_requester_id_fkey', 'follow_request', 'user_account', ['requester_id'], ['id'])
    op.create_foreign_key('follow_request_requested_id_fkey', 'follow_request', 'user_account', ['requested_id'], ['id'])
    # ### end Alembic commands ###
