"""empty message

Revision ID: b78114db6960
Revises: c1ed598901ea
Create Date: 2025-02-15 20:08:38.720250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b78114db6960'
down_revision: Union[str, None] = 'c1ed598901ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_request',
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('requested_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['requested_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('requester_id', 'requested_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follow_request')
    # ### end Alembic commands ###
